/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Alumno;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.AlumnoData;
import modelo.Conexion;
import static vistas.vistaUniversidad.jdpEscritorio;

/**
 *
 * @author Jesus Lucero
 */
class CustomTableModel extends DefaultTableModel {

    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
}

public class vistaAlumnoBuscar extends javax.swing.JInternalFrame {

    private CustomTableModel tablaAlumnos;
    private ArrayList<Alumno> listaAlumnos;
    private ArrayList<Object> columnas;
    private Conexion c = new Conexion();

    public vistaAlumnoBuscar() {
        initComponents();
        tablaAlumnos = new CustomTableModel();
        columnas = new ArrayList<>();
        cabeceraTabla();
        jtAlumnos.setModel(tablaAlumnos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgListar = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jProgressBar1 = new javax.swing.JProgressBar();
        jtfIdAlumno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();
        jbtnModificar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnBuscar = new javax.swing.JButton();
        jrbListarPorId = new javax.swing.JRadioButton();
        jrbListarTodos = new javax.swing.JRadioButton();

        setTitle("Buscar Alumno");

        jtfIdAlumno.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfIdAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdAlumnoActionPerformed(evt);
            }
        });
        jtfIdAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdAlumnoKeyTyped(evt);
            }
        });

        jtAlumnos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtAlumnos);

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnBuscar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        bgListar.add(jrbListarPorId);
        jrbListarPorId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jrbListarPorId.setText("Listar por id");
        jrbListarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbListarPorIdActionPerformed(evt);
            }
        });

        bgListar.add(jrbListarTodos);
        jrbListarTodos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jrbListarTodos.setText("Listar todos");
        jrbListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbListarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnModificar)
                .addGap(18, 18, 18)
                .addComponent(jbtnEliminar)
                .addGap(18, 18, 18)
                .addComponent(jbtnCancelar)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbListarPorId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jbtnBuscar))
                    .addComponent(jrbListarTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jrbListarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbListarPorId)
                    .addComponent(jbtnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnModificar)
                    .addComponent(jbtnEliminar)
                    .addComponent(jbtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdAlumnoActionPerformed

    private void jrbListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbListarTodosActionPerformed
        jtfIdAlumno.setEnabled(false);
    }//GEN-LAST:event_jrbListarTodosActionPerformed

    private void jrbListarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbListarPorIdActionPerformed
        jtfIdAlumno.setEnabled(true);
    }//GEN-LAST:event_jrbListarPorIdActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        if (jrbListarTodos.isSelected()) {
            limpiarTabla();
            listarTodos();
        }
        else if (jrbListarPorId.isSelected()){
            limpiarTabla();
            listarPorId();
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        vistaAlumnoModificar ventanaModificar = new vistaAlumnoModificar();
        jdpEscritorio.add(ventanaModificar);
        ventanaModificar.show();

    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
       
        if (JOptionPane.showInternalConfirmDialog(this, "¿Esta seguro que desea eliminar el alumno?") == 0){
        AlumnoData ad = new AlumnoData(c);
        ad.borrarAlumno((int) tablaAlumnos.getValueAt(jtAlumnos.getSelectedRow(), 0));
        JOptionPane.showMessageDialog(this, "Alumno Borrado");
        jbtnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jtfIdAlumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdAlumnoKeyTyped
        
       
    }//GEN-LAST:event_jtfIdAlumnoKeyTyped
    
    
    public void listarPorId(){
        AlumnoData alumnoData = new AlumnoData(c);
        Alumno alumno = alumnoData.buscarAlumno(Integer.parseInt(jtfIdAlumno.getText()));
        String activo;
        if (alumno.isActivo()) {
            activo = "si";
        } else {
            activo = "no";
        }
        tablaAlumnos.addRow(new Object[]{alumno.getId_alumno(), alumno.getNombre_alumno(), alumno.getFn_alumno(), activo});
      
      }
    
    public void listarTodos() {
        AlumnoData alumnoData = new AlumnoData(c);
        listaAlumnos = alumnoData.buscarAlumnos();

        for (Alumno it : listaAlumnos) {
            String activo;
            if (it.isActivo()) {
                activo = "si";
            } else {
                activo = "no";
            }
            tablaAlumnos.addRow(new Object[]{it.getId_alumno(), it.getNombre_alumno(), it.getFn_alumno(), activo});
        }

    }

    public void limpiarTabla() {
        int x = tablaAlumnos.getRowCount() - 1;
        for (int it = x; it >= 0; it--) {
            tablaAlumnos.removeRow(it);
        }

    }

    public void cabeceraTabla() {
        columnas.add("ID");
        columnas.add("NOMBRE");
        columnas.add("FECHA DE NACIMIENTO");
        columnas.add("ACTIVO");

        for (Object it : columnas) {
            tablaAlumnos.addColumn(it);
        }
        jtAlumnos.setModel(tablaAlumnos);
        jtAlumnos.getTableHeader().setReorderingAllowed(false);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgListar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JRadioButton jrbListarPorId;
    private javax.swing.JRadioButton jrbListarTodos;
    private javax.swing.JTable jtAlumnos;
    private javax.swing.JTextField jtfIdAlumno;
    // End of variables declaration//GEN-END:variables
}
